# -*- coding: utf-8 -*-
"""Product_Recommendation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1boTU4ux9A8aiDKNK39czhfkLreoVsInF
"""

import pandas as pd
import numpy as np
import faiss
from sklearn.feature_extraction.text import TfidfVectorizer
from textblob import TextBlob

data = pd.read_csv(r"E:\ML_project\amazon.csv")

data

#taking only the necessary columns
data = data[['product_name', "category","rating","review_title"]].drop_duplicates().reset_index(drop=True)
data

data.isnull().any()

data=pd.DataFrame(data)

data

data['all_details'] = data['product_name'] + " " + data['category'] +" " + data['rating'] +" " + data['review_title']

data

course_corpus = data['all_details']

course_corpus

from sklearn.feature_extraction.text import TfidfVectorizer

#vectorizer
vectorizer = TfidfVectorizer(analyzer='char_wb', ngram_range=(3,3), min_df=5)
X = vectorizer.fit_transform(course_corpus)
X = np.float32(X.toarray())

X

index = faiss.IndexFlatL2(X.shape[1])
index.add(X)

ip=input("Enter the product name: ")

ip

search_text = [f"{ip}"]
search_text_vector = vectorizer.transform(search_text)
search_text_vector_array = np.float32(search_text_vector.toarray())

distances, indices = index.search(search_text_vector_array, 5)

indices[0]

#fetching names
product_names = [data['product_name'][indices[0][i]] for i in range(len(indices[0]))]
category_names = [data['category'][indices[0][i]] for i in range(len(indices[0]))]
rating_names = [data['rating'][indices[0][i]] for i in range(len(indices[0]))]
review_names = [data['review_title'][indices[0][i]] for i in range(len(indices[0]))]

#converted into dataframes
product_names=pd.DataFrame(product_names)
category_names=pd.DataFrame(category_names)
rating_names=pd.DataFrame(rating_names)
review_names=pd.DataFrame(review_names)

final = pd.concat([product_names, category_names, rating_names, review_names], axis=1)

# Rename the columns
final.columns = ['product_name', 'category', 'rating', 'review_title']

final

# Sort the DataFrame by 'rating' column in descending order
final = final.sort_values(by='rating', ascending=False)

final

from textblob import TextBlob

final['sentiment'] = final['review_title'].apply(lambda x: 'Positive review' if TextBlob(x).sentiment.polarity > 0 else 'Negative review')

final

final.to_excel('product_recommendation.xlsx', index=False)

